FORMAT: 1A

# Uranus

The API Documentation of Project [Uranus](https://github.com/project-uranus).

## References

- https://uranus.docs.apiary.io/
- https://github.com/microsoft/api-guidelines
- https://github.com/georgesmith46/bcbp

## Authentication

JSON Web Token

https://tools.ietf.org/html/rfc7519

- Header
  - alg: SH256
  - typ: JWT
- Payload
  - exp: `timestamp`
  - iss: uranus
  - iat: `timestamp`
  - role: `administrator` | `staff` | `security`| `passenger`
  - identifier: `Long`

## Models

### User

| Name | Type | Example | Note |
| :--- | :--: | :------ | :--- |
| email | `String` | | |
| password | `String` | | md5 |
| name | `String` | John Doe | |
| first_name | `String` | JOHN | |
| last_name | `String` | DOE | |
| id_number | `String` | | |

### Airport

| Name | Type | Example |
| :--- | :--: | :------ |
| name | `String` | 上海浦东国际机场 |
| IATA | `String` | PVG |
| position | `String` | 上海 |
| position_code | `String` | SHA |
| latitude | `Double` | 31.143333 |
| longitude | `Double` | 121.805278 |

### Boarding Pass

https://shaun.net/notes/whats-contained-in-a-boarding-pass-barcode/

| Name | Type | Size | Default | Example | Note |
| :--- | :--: | :--: | :------ | :------ | :--- |
| format_code | `Char` | 1 |  M | | `DEFAULT` |
| number\_of\_legs\_encoded | `Char` | 1 | 1 | | `DEFAULT` |
| passenger_name | `String` | 20 | | DESMARAIS/LUC | `CSV` |
| electronic\_ticket\_indicator | `Char` | 1 | E | | `DEFAULT` |
| operating\_carrier\_PNR\_code | `String` | 7 | | ABC123 |  `DEFAULT` |
| from\_city\_airport\_code | `String` | 3 | | YUL | `IMPORTED` |
| to\_city\_airport\_code | `String` | 3 | | FRA | `IMPORTED` |
| operating\_carrier\_designator | `String` | 3 | | AC | `IMPORTED` |
| flight_number | `String` | 5 | | 0834 | `IMPORTED` |
| date\_of\_flight | `Int` | 3 | | 226 | `IMPORTED` Julian Date |
| compartment_code | `Char` | 1 | | F | `CSV` |
| seat_number | `String` | 4 | | 001A | `CSV` |
| check\_in\_sequence\_number | `String` | 5 | 0000 | 0025 | `DEFAULT` |
| passenger_status | `Char` | 1 | 0 | 0 | |
| field\_size\_of\_variable\_size\_field | `String` | 2 | 00 | 00 | `DEFAULT` Hexiadecimal |

#### Passenger Status


### Counter

| Name | Type | Example |
| :--- | :--: | :------ |
| type | | |
| staff_id | `Int` | |
| is_available | `Bool` | |

### Flight

| Name | Type | Example |
| :--- | :--: | :------ |
| airline | `String` | 中国东方航空 |
| flight_number | `String` | MU291 |
| aircraft | `String` | Airbus A320 |
| date\_of\_flight | `Date` | 2019-12-19 |
| departure_time | `Timestamp` | 2019-12-19T17:15:00Z |
| arrival_time | `Timestamp` | 2019-12-19T20:40:00Z |
| origin_airport | `Airport` | |
| destination_airport | `Airport` | |
| boarding_time | `Time` | 2019-12-19T16:30:00Z |
| boarding_gate | `String` | 2 |
| status | `Char` | 0 |

# Group Authentication

## Sign Up [/auth/sign_up]

### Sign Up [POST]

+ Request (application/json)

    + Headers
            
            Accept: application/json

    + Body

            {
                "phone": "00000000000"
            }
        
+ Response 201 (application/json)

    + Attributes (object)

        + token: `QWxhZGRpbjpvcGVuIHNlc2FtZQ==` (string) - Token    

    + Body
    
            { 
                "token": "QWxhZGRpbjpvcGVuIHNlc2FtZQ=="
            }

+ Response 409 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Conflict",
                    "message": "duplicated e-mail"
                }
            }

### Login [/auth/login]

`administrator` | `staff` | `passenger`

# Group Flight

## Check-in [/checkin]

### Check-in [GET]

`passenger`

+ Request

    + Headers
    
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    
    + Attributes (object)

        + number\_of\_luggages: `1` (number) - The number of luggages to be checked.
        + accompanying_persons (array[string]) - The ID numbers of accompanying persons, **except oneself**.

    + Body

            {
                "number_of_luggages": 1,
                "accompanying_persons": [
                    "11111111",
                    "22222222"
                ]
            }

+ Response 200 (application/json)

    + Attributes (object)

        + counter_id: `1` (number) - The number of counter the passenger assigned to.

    + Body

            {
                "counter_id": 1
            }

+ Response 401 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Unauthorized",
                    "message": "invalid token"
                }
            }

## Boarding Pass [/boardingPass]

### Get Boarding Pass Token [GET]

`passenger`

+ Request

    + Headers
    
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==

+ Response 200 (application/json)

    + Attributes (object)

        + token: `M1DESMARAIS/LUC       EABC123 YULFRAAC 0834 226F001A0025 100` (string) - Token

    + Body
    
            { 
                "token": "M1DESMARAIS/LUC       EABC123 YULFRAAC 0834 226F001A0025 100"
            }

+ Response 401 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Unauthorized",
                    "message": "invalid token"
                }
            }

### Update Passenger Status [PUT]

`staff`

+ Request (application/json)

    + Headers
    
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    
    + Body

            {
                "passenger_status": 'A'
            }

+ Response 200 (application/json)

    + Body
    
            { 
                "token": "M1DESMARAIS/LUC       EABC123 YULFRAAC 0834 226F001A0025 100"
            }

+ Response 401 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Unauthorized",
                    "message": "invalid token"
                }
            }

## Personal Information [/information]

### Get Personal Information [GET]

`administrator` | `staff` | `security`| `passenger` 

+ Request (application/json)

    + Headers
    
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    
+ Response 200 (application/json)

    + Body
    
            { 
                "value": {}
            }

+ Response 401 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Unauthorized",
                    "message": "invalid token"
                }
            }

### Update Personal Information [PUT]

`passenger`

+ Request (application/json)

    + Headers
    
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    
+ Response 200 (application/json)

    + Body
    
            { 
                "value": {}
            }

+ Response 401 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Unauthorized",
                    "message": "invalid token"
                }
            }

## Airports [/airports]

### Get IATA List [GET]

`administrator`

Get the list of available IATA airpode codes.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    
+ Response 200 (application/json)

    + Attributes (object)
        + value (array[string])

    + Body
    
            { 
                "value": [
                    "PVG",
                    "NGO"
                ]
            }

+ Response 401 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Unauthorized",
                    "message": "invalid token"
                }
            }

## Flight [/flight]

### Get Flight list [GET /flights]

`passenger`

Get the list of flights of a specific passenger.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==

+ Response 200 (application/json)

    + Attributes (object)
        + value (array[Flight])

    + Body
    
            { 
                "value": [
                    {
                        "airline": "中国东方航空",
                        "flight_number": "MU291",
                        "aircraft": "Airbus A320",
                        "date_of_flight": "2019-12-19",
                        "departure_time": "2019-12-19T17:15:00Z".
                        "arrival_time": "2019-12-19T20:40:00Z"
                        "origin_airport": {
                            "position": "上海",
                            "position_code": "SHA"
                        },
                        "destination_airport": {
                            "position": "名古屋",
                            "position_code": "NGO"
                        },
                        "status": "scheduled"
                    }
                ]
            }

+ Response 401 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Unauthorized",
                    "message": "invalid token"
                }
            }

### Get Flight Detail [GET /flights/{?flight_id}]

`passenger`

Get the detail of a specific flight according to the ID of flight.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==

+ Parameters

    + flight_id: `ABC123` (optional, string) - Flight ID

+ Response 200 (application/json)

    + Attributes (object)
        + value (Flight Detail)

    + Body

            { 
                "value": {
                    "flight": {
                        "airline": "中国东方航空",
                        "flight_number": "MU291",
                        "aircraft": "Airbus A320",
                        "date_of_flight": "2019-12-19",
                        "departure_time": "2019-12-19T17:15:00Z".
                        "arrival_time": "2019-12-19T20:40:00Z"
                        "origin_airport": {
                            "name": "上海浦东国际机场",
                            "IATA": "PVG",
                            "latitude": "31.143333",
                            "longitude": "121.805278"
                        },
                        "destination_airport": {
                            "name": "中部国际机场",
                            "IATA": "NGO",
                            "latitude": "34.858333",
                            "longitude": "136.805278"
                        },
                        "boarding_time": "2019-12-19T16:30:00Z",
                        "boarding_gate": "2",
                        "status": "scheduled"
                    },
                    "spec": {
                        "compartment_code": "F",
                        "seat_number": "1A",
                    }
                }
            }

+ Response 401 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Unauthorized",
                    "message": "invalid token"
                }
            }
   
### Create Flight [POST /flights/{?flight_id}]

`administrator`

+ Request (application/json)

    + Headers
    
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    
    + Body

            {
                "airline": "中国东方航空",
                "flight_number": "MU291",
                "aircraft": "Airbus A320",
                "date_of_flight": "2019-12-19",
                "departure_time": "2019-12-19T17:15:00Z".
                "arrival_time": "2019-12-19T20:40:00Z"
                "origin_airport": "SHA",
                "destination_airport": "NGO",
                "boarding_time": "2019-12-19T16:30:00Z".
                "boarding_gate": "2"
            }

+ Response 200 (application/json)

+ Response 401 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Unauthorized",
                    "message": "invalid token"
                }
            }

### Update Flight [PUT]

`administrator`

+ Request (application/json)

    + Headers
    
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    
    + Body

            {
                "passenger_status": 'A'
            }

+ Response 200 (application/json)

+ Response 401 (application/json)

    + Attributes (Error)

    + Body
    
            { 
                "error": {
                    "code": "Unauthorized",
                    "message": "invalid token"
                }
            }

# Group WebSocket

# Data Structures

## Error (object)

+ error (object)
    + code: `Bad Request` (string) - HTTP status codes
    + message: `Message` (string) - Custom message

## Airport (object)

+ name: `上海浦东国际机场` (string) - Name
+ IATA: `PVG` (string) - IATA airport code
+ position: `上海` (string) - Position
+ position_code: `SHA` (string) - Position code
+ latitude: `31.143333` (string) - Latitude
+ longitude: `121.805278` (string) - Longtitude

## Flight (object)

+ airline: `中国东方航空` (string) - Airline
+ flight_number: `MU291` (string) - Flight number
+ aircraft: `Airbus A320` (string) - Aircraft
+ date_of_flight: `2019-12-19` (string) - Date of flight
+ departure_time: `2019-12-19T17:15:00Z` (string) - Time of Departure
+ arrival_time: `2019-12-19T20:40:00Z` (string) - Time of Arrival
+ origin_airport (Airport)
+ destination_airport (Airport)
+ boarding_time: `2019-12-19T16:30:00Z` (string) - Time of Boarding
+ boarding_gate: `2` (string)
+ status: `scheduled` (enum[string]) - Status of Flight

    + Members
    
        + `scheduled` - 已排定
        + `delayed` - 已延误
        + `boarding` - 登机中
        + `departed` - 已出发
        + `arrived` - 已到达
        + `cancelled` - 已取消
        + `noTakeoffInfo` - 无

## Flight Detail (object)

+ flight (Flight)
+ spec (object)
    + compartment_code: `F` (enum[string]) - Code of Compartment
    
        + Members
            
            + `F` - First Class
            + `C` - Business Class
            + `Y` - Economy Class

    + seat_number: `1A` (string) - Number of Seat

## Passenger Status (object)

+ passenger_status: `0` (enum[number])

    + Members

        + `0` - Ticket issuance/passenger not checked in
        + `1` - Ticket issuance/passenger checked in
        + `2` - Bag checked/passenger not checked in
        + `3` - Bag checked/passenger checked in
        + `7` - Standby
        + `8` - Boarding data revalidation done